In [1]:
import torch

In [28]:
rewards = torch.cumsum(torch.ones(10), dim=-1)
successor_value_estimates = torch.cumsum(torch.ones(10)*2, dim=-1)
gamma = 0.99
n = 4



In [ ]:
torch.stack

In [29]:
discounted_succ_values = successor_value_estimates[n:]
discounted_succ_values = torch.cat([discounted_succ_values, torch.ones(n)*discounted_succ_values[-1]], dim=0)

In [30]:
discounted_succ_values

tensor([10., 12., 14., 16., 18., 20., 20., 20., 20., 20.])

In [31]:
rewards

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [25]:
torch.stack?

In [20]:
discounted_succ_values

tensor([10., 12., 14., 16., 18., 20.])

In [41]:
n = 4
discounted_rewards = []
len_sequence = len(rewards)
for idx in range(len_sequence):
    n = min(len_sequence - idx, n)
    terms_to_discount = rewards[idx:idx+n]
    discount_factors = torch.as_tensor([gamma**i for i in range(n)], dtype=torch.float32)
    discounted_reward = terms_to_discount * discount_factors + gamma**(n+1)+successor_value_estimates[idx]
    discounted_rewards.append(discounted_reward)
    

0 tensor([1., 2., 3., 4.])
torch.Size([4]) torch.Size([4])
1 tensor([2., 3., 4., 5.])
torch.Size([4]) torch.Size([4])
2 tensor([3., 4., 5., 6.])
torch.Size([4]) torch.Size([4])
3 tensor([4., 5., 6., 7.])
torch.Size([4]) torch.Size([4])
4 tensor([5., 6., 7., 8.])
torch.Size([4]) torch.Size([4])
5 tensor([6., 7., 8., 9.])
torch.Size([4]) torch.Size([4])
6 tensor([ 7.,  8.,  9., 10.])
torch.Size([4]) torch.Size([4])
7 tensor([ 8.,  9., 10.])
torch.Size([3]) torch.Size([3])
8 tensor([ 9., 10.])
torch.Size([2]) torch.Size([2])
9 tensor([10.])
torch.Size([1]) torch.Size([1])


In [10]:
rewards

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [14]:
rewards.unfold(-1, 4, 1)

tensor([[ 1.,  2.,  3.,  4.],
        [ 2.,  3.,  4.,  5.],
        [ 3.,  4.,  5.,  6.],
        [ 4.,  5.,  6.,  7.],
        [ 5.,  6.,  7.,  8.],
        [ 6.,  7.,  8.,  9.],
        [ 7.,  8.,  9., 10.]])

In [15]:
rewards.unfold?

In [ ]:
rewards

In [5]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [6]:
torch.triu(torch.ones(3,3))

tensor([[1., 1., 1.],
        [0., 1., 1.],
        [0., 0., 1.]])

In [ ]:
rewards + gamma*rewards

In [51]:
# TODO: WRITE THIS FUNCTION
def calculate_n_step_return(
    rewards: torch.Tensor,
    successor_value_estimates: torch.Tensor,
    n: int,
    gamma: float,
) -> torch.Tensor:
    """
    Calculate the n-step return for each timestep in the episode.

    n-step return = r_{t+1} + gamma * r_{t+2} + ... + gamma^{n-1} * r_{t+n} + gamma^n * V(s_{t+n})
    """
    
    discounted_rewards = []
    len_sequence = len(rewards)
    for idx in range(len_sequence):
        n = min(len_sequence - idx, n)
        terms_to_discount = rewards[idx:idx+n]
        discount_factors = torch.as_tensor([gamma**i for i in range(n)], dtype=torch.float32)
        discounted_reward = (terms_to_discount * discount_factors).sum() + gamma**(n+1)+successor_value_estimates[idx]
        discounted_rewards.append(discounted_reward)
    return torch.as_tensor(discounted_rewards, dtype=torch.float32)

In [52]:
rewards = torch.ones(100)
successor_value_estimates = torch.zeros(100)
n = 120
gamma = 0.99

calculate_n_step_return(rewards, 
                        successor_value_estimates, 
                        n,
                        gamma)

100
tensor(63.7591)


tensor([63.7591, 63.3931, 63.0233, 62.6498, 62.2725, 61.8914, 61.5065, 61.1177,
        60.7249, 60.3282, 59.9275, 59.5227, 59.1139, 58.7009, 58.2837, 57.8623,
        57.4367, 57.0068, 56.5725, 56.1338, 55.6907, 55.2432, 54.7911, 54.3344,
        53.8731, 53.4072, 52.9366, 52.4612, 51.9810, 51.4960, 51.0060, 50.5111,
        50.0112, 49.5063, 48.9963, 48.4811, 47.9607, 47.4350, 46.9041, 46.3678,
        45.8260, 45.2788, 44.7261, 44.1677, 43.6038, 43.0341, 42.4587, 41.8775,
        41.2904, 40.6974, 40.0984, 39.4933, 38.8821, 38.2648, 37.6412, 37.0113,
        36.3750, 35.7323, 35.0832, 34.4275, 33.7651, 33.0961, 32.4203, 31.7376,
        31.0481, 30.3516, 29.6481, 28.9375, 28.2197, 27.4946, 26.7623, 26.0225,
        25.2752, 24.5204, 23.7580, 22.9879, 22.2100, 21.4243, 20.6306, 19.8288,
        19.0190, 18.2010, 17.3748, 16.5402, 15.6972, 14.8456, 13.9855, 13.1166,
        12.2390, 11.3526, 10.4571,  9.5527,  8.6390,  7.7162,  6.7841,  5.8425,
         4.8914,  3.9307,  2.9603,  1.98